version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
     - PMA_ARBITRARY=1
    ports:
      - 8890:80
    links:
      - db

  wordpress:
    build:
      context: ./config/wordpress
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./data/files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress