version: '3'

services:
  db:
    container_name: db
    image: mariadb:latest
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    env_file:
      - ./.env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    env_file:
      - ./.env
    ports:
      - 8890:80
    links:
      - db

  wordpress:
    container_name: wordpress
    build:
      context: ./config/wordpress
      args:
        - PHP_VERSION=$PHP_VERSION
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./data/files:/var/www/html
      - ./config/wordpress/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - ./.env
